# Generated by Django 5.2.17 on 2026-09-07 10:04
#
# MERGED: This migration replaces the old 0002_audioclip_cover_image.py and
# 0002_scraper_license_flags.py which conflicted (two files both numbered 0002).
# All operations from both files are combined here so Django sees a single
# leaf node after 0001_initial.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        # Added by old 0002_audioclip_cover_image.py
        migrations.AddField(
            model_name='audioclip',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%d/'),
        ),
        # Added by old 0002_scraper_license_flags.py
        migrations.AddField(
            model_name='audioclip',
            name='is_noncommercial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audioclip',
            name='requires_share_alike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audioclip',
            name='license_family',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        # SECURITY: Index supports fast feed exclusion of NC + SA items.
        migrations.AddIndex(
            model_name='audioclip',
            index=models.Index(
                fields=['is_noncommercial', '-created_at'],
                name='audioclip_nc_created_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='audioclip',
            index=models.Index(
                fields=['requires_share_alike', '-created_at'],
                name='audioclip_sa_created_idx',
            ),
        ),
    ]
